### ISSUE TITLE
Does not work two-color gradient

### ISSUE THREAD

**Issue by exxpploit** [maxludden/rich-gradient#1]
This code works:
```python
from rich.console import Console
from rich_gradient import Gradient

console = Console()

console.print(
    Gradient(
        "This a gradient with specific colors.",
        colors=['#ff0f7b', '#f89b29', '#f89b29'],
        justify="center",
    )
)
```

But this one is not
```python
from rich.console import Console
from rich_gradient import Gradient

console = Console()

console.print(
    Gradient(
        "This a gradient with specific colors.",
        colors=['#ff0f7b', '#f89b29'],
        justify="center",
    )
)
```

IndexError: list index out of range

**Comment by maxludden** [comment]
Hey,

Thanks for pointing it out… I always thought that simple gradients were kind of boring so I never thought to test it. But I just pushed `v0.1.7` with the ability to create gradients with two specific colors only. 

![Specific Two-Color Gradients](https://raw.githubusercontent.com/maxludden/rich-gradient/abd87b9116c0722dbd938b081aaa5fb846d4eb21/docs/img/specific_two_color_gradient.svg)

I hope this helps you make whatever gradients you would like. I've updated the `README.md` page and am in the process up dating the docs to let others know. Again, thank you for using `rich-gradient`, and I hope you find it easier to use now.

Max Ludden

**Comment by maxludden** [comment]
`rich-gradient` allows the printing of gradients with two specific colors now. I know it should have always, and that was an oversight on my part… but I always liked at least three colors personally - so I forgot to to test for two. Apologies.
